permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true
markdown: kramdown

name: "Alexis Tabary"
description: "Python and Elixir Full Stack developer in Japan"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
